name: Changelog Reminder

on: pull_request
permissions:
  pull-requests: write
jobs:
  remind:
    name: Changelog Reminder
    runs-on: ubuntu-latest
    if: github.repository == 'raycast/extensions'
    steps:
      - uses: actions/checkout@v3
      - uses: mskelton/changelog-reminder-action@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          message: "omgz"
