# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Close stale issues and PRs

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-stale-workflow]
  pull_request_target:
    paths:
      - "extensions/**"
    branches: [main, master]
  issues:
    types: ["edited"]
  issue_comment:
    types: ["edited"]

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    if: github.repository == 'raycast/extensions'
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.RAYCAST_BOT_API_ACCESS_TOKEN }}

          # Issues
          stale-issue-message: "This issue has been automatically marked as stale because it did not have any recent activity.\n\nIt will be closed if no further activity occurs in the next 10 days to keep our backlog clean ðŸ˜Š"
          close-issue-message: "This issue has been automatically closed due to inactivity.\n\nFeel free to comment in the thread when you're ready to continue working on it ðŸ™‚\n\nYou can also catch us in [Slack](https://www.raycast.com/community) if you want to discuss this."
          exempt-issue-labels: "api, documentation, dev tools, app, status: blocked by API, rename, Dont close"
          stale-issue-label: "status: stalled"
          days-before-issue-stale: 50
          days-before-issue-close: 10

          # PRs
          stale-pr-message: "This pull request has been automatically marked as stale because it did not have any recent activity.\n\nIt will be closed if no further activity occurs in the next 14 days to keep our backlog clean ðŸ˜Š"
          close-pr-message: "This pull request has been automatically closed due to inactivity.\n\nFeel free to comment in the thread when you're ready to continue working on it ðŸ™‚\n\nYou can also catch us in [Slack](https://www.raycast.com/community) if you want to discuss this."
          exempt-pr-labels: "api, documentation, dev tools, app, status: blocked by API, rename, Dont close, AI Extension, Windows"
          stale-pr-label: "status: stalled"
          days-before-pr-stale: 21
          days-before-pr-close: 7

          # Limiting
          operations-per-run: 400

          # Debug
          #debug-only: true
